# Generated by Django 5.1 on 2025-03-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0044_photo_comment_share_like_photoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(),
        ),
    ]
