# Generated by Django 5.1 on 2025-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0046_alter_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
