# Generated by Django 5.1 on 2025-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0047_user_reg_reset_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preminder',
            old_name='task_title',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='task_title',
            new_name='venue',
        ),
    ]
