# Generated by Django 5.1 on 2025-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0048_rename_task_title_preminder_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_reg',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
